#!/usr/bin/env bash
# generate_memory_map.sh — scan meta/*.md nodes and rebuild MEMORY_MAP.md
# Also auto-computes blocks (reverse depends_on) and validates topology.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$SCRIPT_DIR/..")"
META_DIR="${PROJECT_ROOT}/meta"
OUTPUT="${PROJECT_ROOT}/MEMORY_MAP.md"

if [ ! -d "$META_DIR" ]; then
  echo "No meta/ directory found at $META_DIR. Nothing to index."
  exit 0
fi

# ─── Extract a YAML scalar field (single-line) ────────────────────────
extract_scalar() {
  local key="$1" fm="$2"
  echo "$fm" | sed -n "s/^${key}:[[:space:]]*//p" | tr -d '"' | xargs
}

# ─── Extract a YAML list field — handles BOTH formats ─────────────────
#   tags: [auth, login, jwt]          ← inline
#   tags:                             ← multi-line
#     - auth
#     - login
extract_list() {
  local key="$1" fm="$2"

  # Try inline first: key: [a, b]
  local inline
  inline=$(echo "$fm" | sed -n "/^${key}:[[:space:]]*\[/s/^${key}:[[:space:]]*//p" | tr -d '[]"' | tr ',' ' ')
  if [ -n "$(echo "$inline" | xargs)" ]; then
    echo "$inline" | xargs
    return
  fi

  # Multi-line: key:\n  - a\n  - b
  echo "$fm" | awk -v k="$key" -v in_list=0 '
    $0 ~ ("^" k ":[[:space:]]*$") { in_list=1; next }
    in_list && /^[[:space:]]*-[[:space:]]+/ {
      item = $0
      sub(/^[[:space:]]*-[[:space:]]*/, "", item)
      gsub(/["\47\],]/, "", item)
      sub(/[[:space:]]+$/, "", item)
      if (item != "") printf "%s\n", item
      next
    }
    in_list && /^[[:space:]]*$/ { next }
    in_list && /^[a-zA-Z]/ { in_list=0 }
  '
}

# ─── Parse a single node file ─────────────────────────────────────────
parse_node() {
  local file="$1"
  local rel="${file#$PROJECT_ROOT/}"

  local fm
  fm=$(awk '/^---$/ {c++; next} c==1' "$file" 2>/dev/null || true)
  [ -z "$fm" ] && return

  local id type status updated tags depends_on
  id=$(extract_scalar "id" "$fm")
  type=$(extract_scalar "type" "$fm")
  status=$(extract_scalar "status" "$fm")
  updated=$(extract_scalar "updated" "$fm")
  tags=$(extract_list "tags" "$fm" | tr '\n' ',' | sed 's/,$//')
  depends_on=$(extract_list "depends_on" "$fm" | tr '\n' ',' | sed 's/,$//')

  # Skip archived
  [ "$status" = "archived" ] && return

  echo "${id:-unknown}|${type:-unknown}|${status:-unknown}|${updated:-}|${tags}|${depends_on}|${rel}"
}

# ─── First pass: collect all nodes ─────────────────────────────────────
declare -A NODE_DEPS     # rel_path -> comma-separated depends_on
declare -A NODE_INFO     # rel_path -> full parsed line
declare -a ALL_NODES

while IFS= read -r -d '' file; do
  result=$(parse_node "$file")
  if [ -n "$result" ]; then
    IFS='|' read -r id type status updated tags deps rel <<< "$result"
    ALL_NODES+=("$result")
    NODE_DEPS["$rel"]="$deps"
    NODE_INFO["$rel"]="$result"
  fi
done < <(find "$META_DIR" -maxdepth 2 -name '*.md' ! -name 'MEMORY_MAP.md' -print0 2>/dev/null || true)

# ─── Compute blocks = reverse(depends_on) ──────────────────────────────
declare -A NODE_BLOCKS  # rel_path -> space-separated list of paths that depend on it
for rel in "${!NODE_DEPS[@]}"; do
  deps="${NODE_DEPS[$rel]}"
  [ -z "$deps" ] && continue
  IFS=',' read -ra DEP_ARR <<< "$deps"
  for d in "${DEP_ARR[@]}"; do
    d=$(echo "$d" | xargs)
    [ -z "$d" ] && continue
    NODE_BLOCKS["$d"]="${NODE_BLOCKS[$d]:-} ${rel}"
  done
done

# ─── Build tag index ───────────────────────────────────────────────────
declare -A TAG_MAP  # tag -> newline-separated "id | rel | deps | blocks"
for rel in "${!NODE_INFO[@]}"; do
  result="${NODE_INFO[$rel]}"
  IFS='|' read -r id type status updated tags deps _ <<< "$result"
  blocks=$(echo "${NODE_BLOCKS[$rel]:-}" | xargs | tr ' ' ',')

  IFS=',' read -ra TAGS <<< "$tags"
  for tag in "${TAGS[@]}"; do
    tag=$(echo "$tag" | xargs)
    [ -z "$tag" ] && continue
    tag_lower=$(echo "$tag" | tr '[:upper:]' '[:lower:]')
    TAG_MAP["$tag_lower"]="${TAG_MAP[$tag_lower]:-}${id}|${rel}|${deps}|${blocks}
"
  done
done

# ─── Write MEMORY_MAP.md ───────────────────────────────────────────────
set +u  # allow optional frontmatter fields
{

  echo '<!-- AUTO-GENERATED by scripts/generate_memory_map.sh. DO NOT EDIT MANUALLY. -->'
  echo "# Project Memory Graph Index"
  echo
  echo "## Tag Index"
  echo

  if [ ${#TAG_MAP[@]} -eq 0 ]; then
    echo "No active memory nodes found."
    echo
  else
    for tag in $(printf '%s\n' "${!TAG_MAP[@]}" | sort); do
      echo "### \`$tag\`"
      echo
      printf '%s' "${TAG_MAP[$tag]}" | sort -t'|' -k1,1 -u | while IFS='|' read -r nid nrel ndeps nblocks; do
        echo "- **$nid** — \`$nrel\`"
        [ -n "$ndeps" ] && echo "  depends_on: $(echo "$ndeps" | sed 's/,/, /g')"
        [ -n "$nblocks" ] && echo "  blocks: $(echo "$nblocks" | sed 's/,/, /g')"
      done
      echo
    done
  fi

  echo "## All Active Nodes"
  echo

  if [ ${#ALL_NODES[@]} -eq 0 ]; then
    echo "None."
  else
    for entry in $(printf '%s\n' "${ALL_NODES[@]}" | sort -t'|' -k2,2 -k1,1); do
      IFS='|' read -r nid ntype nstatus nupdated ntags ndeps nrel <<< "$entry"
      case "$ntype" in
        module) pfx="[mod]" ;;
        feature) pfx="[feat]" ;;
        *) pfx="[$ntype]" ;;
      esac
      nblocks=$(echo "${NODE_BLOCKS[$nrel]:-}" | xargs | tr ' ' ',')
      echo "- $pfx **$nid** ($nstatus) — \`$nrel\`"
      [ -n "$nupdated" ] && echo "  updated: $nupdated"
      [ -n "$ndeps" ] && echo "  depends_on: $(echo "$ndeps" | sed 's/,/, /g')"
      [ -n "$nblocks" ] && echo "  blocks: $(echo "$nblocks" | sed 's/,/, /g')"
    done
    echo
  fi

  # ─── Status Digest (lightweight global overview, ~1 line per node) ──
  echo "## Status Digest"
  echo
  for nrel in $(printf '%s\n' "${!NODE_INFO[@]}" | sort); do
    nrel_clean=$(echo "$nrel" | xargs)
    [ -z "$nrel_clean" ] && continue
    result="${NODE_INFO[$nrel_clean]}"
    IFS='|' read -r nid ntype nstatus nupdated ntags ndeps _ <<< "$result"
    [ -z "$nid" ] && continue
    # Count open issues
    issue_cnt=0
    fpath="${PROJECT_ROOT}/${nrel_clean}"
    if [ -f "$fpath" ]; then
      issue_cnt=$(awk '/^## Open Issues$/,/^## / { if (/^- /) c++ } END { print c+0 }' "$fpath" 2>/dev/null || echo 0)
      last_ch=$(awk '/^## Change Log$/,/^$|^---$/ { if (/^- /) { print; exit } }' "$fpath" 2>/dev/null | sed 's/^- //' | xargs 2>/dev/null || true)
    fi
    echo "- **$nid** ($nstatus, updated: ${nupdated:-?}, ${issue_cnt:-0} open issues)"
    [ -n "${last_ch:-}" ] && echo "  Last: $last_ch"
    [ -n "${ndeps:-}" ] && [ "$ndeps" != " " ] && echo "  depends_on: $(echo "$ndeps" | sed 's/,/, /g')"
    nblocks=$(echo "${NODE_BLOCKS[$nrel_clean]:-}" 2>/dev/null | xargs 2>/dev/null | tr ' ' ',' 2>/dev/null || true)
    [ -n "${nblocks:-}" ] && [ "$nblocks" != " " ] && echo "  blocks: $(echo "$nblocks" | sed 's/,/, /g')"
  done
  echo

  # ─── Topology validation ─────────────────────────────────────────────
  echo "## Topology Health"
  echo

  warnings=0

  # Dead links
  for rel in "${!NODE_DEPS[@]}"; do
    deps="${NODE_DEPS[$rel]}"
    [ -z "$deps" ] && continue
    IFS=',' read -ra DEP_ARR <<< "$deps"
    for d in "${DEP_ARR[@]}"; do
      d=$(echo "$d" | xargs)
      [ -z "$d" ] && continue
      if [ ! -f "${PROJECT_ROOT}/${d}" ]; then
        echo "- ⚠ DEAD LINK: \`$rel\` depends_on \`$d\` — file not found"
        warnings=$((warnings + 1))
      fi
    done
  done

  # Cycle detection (A depends_on B, B depends_on A — using full rel paths)
  declare -A CYCLE_SEEN
  for rel in "${!NODE_DEPS[@]}"; do
    deps="${NODE_DEPS[$rel]}"
    [ -z "$deps" ] && continue
    IFS=',' read -ra DEP_ARR <<< "$deps"
    for d in "${DEP_ARR[@]}"; do
      d=$(echo "$d" | xargs)
      [ -z "$d" ] && continue
      # Build a normalized pair key (sorted) to avoid duplicate reports
      if [[ "$rel" < "$d" ]]; then pair="$rel|||$d"; else pair="$d|||$rel"; fi
      [ "${CYCLE_SEEN[$pair]:-}" = "1" ] && continue
      CYCLE_SEEN["$pair"]=1
      d_deps="${NODE_DEPS[$d]:-}"
      if echo "${d_deps}," | grep -qF "${rel},"; then
        echo "- 🔄 CYCLE: \`$rel\` ⇄ \`$d\` — mutual dependency (OK for some patterns, flag if unintentional)"
        warnings=$((warnings + 1))
      fi
    done
  done

  # Orphan nodes (no deps, no blocks)
  for rel in "${!NODE_INFO[@]}"; do
    deps="${NODE_DEPS[$rel]}"
    blocks="${NODE_BLOCKS[$rel]:-}"
    if [ -z "$(echo "$deps" | xargs)" ] && [ -z "$(echo "$blocks" | xargs)" ]; then
      IFS='|' read -r nid _ <<< "${NODE_INFO[$rel]}"
      echo "- ⚪ ORPHAN: \`$rel\` ($nid) — no edges in either direction"
      warnings=$((warnings + 1))
    fi
  done

  # Node size check (warn if > 200 lines)
  for rel in "${!NODE_INFO[@]}"; do
    fpath="${PROJECT_ROOT}/${rel}"
    if [ -f "$fpath" ]; then
      lines=$(wc -l < "$fpath" 2>/dev/null || echo 0)
      if [ "$lines" -gt 200 ]; then
        IFS='|' read -r nid _ <<< "${NODE_INFO[$rel]}"
        echo "- 📦 OVERSIZED: \`$rel\` ($nid) — $lines lines. Consider splitting into sub-nodes."
        warnings=$((warnings + 1))
      fi
    fi
  done

  if [ "$warnings" -eq 0 ]; then
    echo "✅ No topology issues detected."
  fi

  echo
  echo "---"
  echo "Generated $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "${#ALL_NODES[@]} active nodes, ${#TAG_MAP[@]} tags, $warnings warnings"

} > "$OUTPUT"
set -u

echo "MEMORY_MAP.md regenerated: ${#ALL_NODES[@]} nodes, ${#TAG_MAP[@]} tags, $warnings topology warnings."
